import type { MobileLocale } from "./types";

const copy = {
  en: {
    appName: "Borbodhu",
    appSubtitle: "Trusted Bangladeshi matchmaking and wedding planning",
    welcomeEyebrow: "বরবধূ · Borbodhu",
    welcomeBody:
      "Trusted Bangladeshi matrimony for home and diaspora. Find your life partner, connect with a Ghotok, and plan your perfect wedding.",
    login: "Log In",
    signup: "Sign Up",
    signout: "Sign Out",
    reload: "Refresh",
    email: "Email",
    password: "Password",
    firstName: "First name",
    lastName: "Last name",
    displayNameLabel: "Display name",
    gender: "Gender",
    lookingFor: "Looking for",
    man: "Man",
    woman: "Woman",
    locale: "Language",
    chooseLocale: "Choose your app language",
    loginHint: "Log in with your email and password to access your profile and matches.",
    signupHint: "Create a member profile directly from the mobile app.",
    loggingIn: "Logging in...",
    signingUp: "Creating account...",
    loading: "Loading your Borbodhu mobile workspace...",
    roleDashboard: "Your Borbodhu Dashboard",
    memberOverview: "Member Overview",
    adminOverview: "Admin Overview",
    superAdminOverview: "Super Admin",
    vendorOverview: "Vendor Overview",
    vendorProfileLabel: "Vendor profile",
    ghotokOverview: "Ghotok Overview",
    profileComplete: "Profile complete",
    profileVisits: "Profile visits",
    interests: "Interests",
    photoRequests: "Photo requests",
    pendingProfiles: "Pending profiles",
    collectedAmount: "Collected amount",
    manualReview: "Manual review",
    members: "Members",
    vendors: "Vendors",
    plans: "Plans",
    revenue: "Revenue",
    creditBalance: "Credit balance",
    managedMembers: "Managed members",
    recentMatches: "Recent matches",
    recentLeads: "Recent leads",
    mailbox: "Mailbox",
    wedding: "Wedding",
    vendorsDirectory: "Vendors",
    profileTab: "Profile",
    reviewQueue: "Review queue",
    manualPaymentsLabel: "Manual payments",
    managedList: "Managed members",
    packagesLabel: "Packages",
    overviewTab: "Overview",
    matchesTab: "Matches",
    leadsTab: "Leads",
    membersTab: "Members",
    weddingProjects: "Wedding projects",
    vendorShortlists: "Vendor shortlist",
    conversations: "Conversations",
    profileSettings: "Profile settings",
    partnerPreferences: "Partner preferences",
    photoRequestsLabel: "Photo requests",
    mediaLibrary: "Photos",
    uploadPhoto: "Upload photo",
    photoFromPhone: "Pick from phone",
    photoFromCamera: "Take photo",
    membershipPlans: "Membership plans",
    orderHistory: "Order history",
    messages: "Messages",
    startChat: "Start chat",
    openChat: "Open chat",
    typeMessage: "Type a message",
    sendMessage: "Send message",
    noConversations: "No conversations yet.",
    noMessages: "No messages yet in this conversation.",
    noProjects: "No wedding projects yet.",
    createProject: "Create project",
    projectTitle: "Project title",
    guestName: "Guest name",
    addGuest: "Add guest",
    shortlistVendor: "Shortlist vendor",
    noVendors: "No vendors found yet.",
    noReviews: "No pending profile reviews right now.",
    noPayments: "No manual payments waiting right now.",
    approve: "Approve",
    reject: "Reject",
    saveProfile: "Save profile",
    savePreferences: "Save preferences",
    submitReview: "Submit for review",
    buyWithAmarPay: "Buy with AmarPay",
    buyWithPaypal: "Buy with PayPal",
    buyWithOffice: "Office payment",
    buyWithManual: "Manual payment",
    publicProfile: "Public profile",
    privateMedia: "Private",
    publicMedia: "Public",
    makePrimary: "Make primary",
    incoming: "Incoming",
    outgoing: "Outgoing",
    ageRange: "Age range",
    guardianPhone: "Guardian phone",
    religionLabel: "Religion",
    professionLabel: "Profession",
    aboutMeLabel: "About me",
    familyDetailsLabel: "Family details",
    aboutPartnerLabel: "About partner",
    locationLabel: "Current city",
    countryCode: "Country code",
    saveSuccessProfile: "Profile saved.",
    saveSuccessPreference: "Preferences saved.",
    submittedForReview: "Profile sent for review.",
    photoRequestApproved: "Photo request approved.",
    photoRequestDenied: "Photo request denied.",
    mediaUpdated: "Photo settings updated.",
    membershipOrderCreated: "Membership order created.",
    noOrders: "No membership orders yet.",
    noMedia: "No photos uploaded yet.",
    noPhotoRequests: "No photo requests yet.",
    uploadSuccessPhoto: "Photo uploaded and sent for review.",
    uploadPermissionError: "Photo access is needed to upload from your phone.",
    ghotokCreateMember: "Add managed member",
    ghotokDiscover: "Discover",
    memberEmailLabel: "Member email",
    memberPhoneLabel: "Member phone",
    countryCodeLabel: "Country code",
    startImpersonation: "Start impersonation",
    endImpersonation: "End impersonation",
    viewContact: "View contact",
    contactUnlocked: "Contact unlocked.",
    activeImpersonationNeeded: "Start an impersonation session first to spend credit.",
    noPublicProfiles: "No public profiles available right now.",
    guardianPhoneLabel: "Guardian phone",
    guardianEmailLabel: "Guardian email",
    impersonationStarted: "Impersonation started.",
    impersonationEnded: "Impersonation ended.",
    managedMemberCreated: "Managed member created.",
    open: "Open",
    responded: "Responded",
    booked: "Booked",
    closeLead: "Close lead",
    conversationStarted: "Conversation ready.",
    messageSent: "Message sent.",
    projectCreated: "Wedding project created.",
    guestAdded: "Guest added.",
    vendorShortlistedSuccess: "Vendor shortlisted.",
    profileApprovedNotice: "Profile approved.",
    profileRejectedNotice: "Profile rejected.",
    paymentApprovedNotice: "Payment approved.",
    paymentRejectedNotice: "Payment rejected.",
    leadUpdatedNotice: "Lead updated.",
    noManagedMembers: "No managed members yet.",
    activeImpersonation: "Active impersonation",
    noImpersonation: "No active impersonation session.",
    guestCount: "Guests",
    shortlistCount: "Shortlists",
    packageCount: "Packages",
    packageNameEn: "Package name (EN)",
    packageNameBn: "Package name (BN)",
    packageDescEn: "Package description (EN)",
    packageDescBn: "Package description (BN)",
    packagePriceBdt: "Price (BDT)",
    createPackage: "Create package",
    editPackage: "Edit package",
    updatePackage: "Update package",
    saveVendorProfile: "Save vendor profile",
    vendorProfileUpdated: "Vendor profile updated.",
    allLabel: "All",
    packageCreatedNotice: "Vendor package created.",
    packageStatusUpdated: "Package status updated.",
    packageLoadedForEdit: "Package loaded for editing.",
    noPackages: "No packages yet.",
    paymentGatewayPending: "Order created. Gateway redirect URL is the next integration step on the test stack.",
    paymentManualPending: "Order created and waiting for admin approval.",
    leadSource: "Lead source",
    createdOn: "Created",
    lastUpdated: "Updated",
    budget: "Budget",
    weddingDateLabel: "Wedding date",
    noMatches: "No matches yet for this member.",
    noLeads: "No vendor leads yet.",
    cityPending: "Location pending",
    liveApiNote: "Live API data",
    mobileNext:
      "Next mobile slices will deepen profile editing, media uploads, payments, and ghotok/vendor actions.",
    profileStatus: "Profile status",
    approvalStatus: "Approval status",
    billingStatus: "Billing status",
    active: "Active",
    pending: "Pending",
    newLabel: "New",
    manualApproved: "Manual approved",
    manualRejected: "Manual rejected",
    approved: "Approved",
    rejected: "Rejected",
    cancelled: "Cancelled",
    inactive: "Inactive",
    paid: "Paid",
    openStatus: "Open",
    closedRejected: "Closed",
    draftStatus: "Draft",
    archivedStatus: "Archived",
    freeMember: "Free member",
    errorTitle: "Something needs attention",
  },
  bn: {
    appName: "বরবধূ",
    appSubtitle: "বিশ্বস্ত বাংলাদেশি ম্যাচমেকিং এবং ওয়েডিং প্ল্যানিং",
    welcomeEyebrow: "মোবাইল অ্যাপ প্রিভিউ",
    welcomeBody:
      "এই অ্যাপটি লাইভ Borbodhu টেস্ট API-এর সাথে কথা বলে যাতে আমরা মোবাইলে বাস্তব লগ ইন, রোল অ্যাক্সেস, এবং ড্যাশবোর্ড আচরণ যাচাই করতে পারি।",
    login: "লগ ইন",
    signup: "সাইন আপ",
    signout: "সাইন আউট",
    reload: "রিফ্রেশ",
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    firstName: "নামের প্রথম অংশ",
    lastName: "নামের শেষ অংশ",
    displayNameLabel: "প্রদর্শিত নাম",
    gender: "লিঙ্গ",
    lookingFor: "খুঁজছেন",
    man: "পুরুষ",
    woman: "নারী",
    locale: "ভাষা",
    chooseLocale: "অ্যাপের ভাষা বেছে নিন",
    loginHint: "আপনার ইমেইল ও পাসওয়ার্ড দিয়ে লগ ইন করুন। আপনার প্রোফাইল ও ম্যাচ দেখতে পারবেন।",
    signupHint: "মোবাইল অ্যাপ থেকেই একটি মেম্বার প্রোফাইল তৈরি করুন।",
    loggingIn: "লগ ইন হচ্ছে...",
    signingUp: "অ্যাকাউন্ট তৈরি হচ্ছে...",
    loading: "আপনার বরবধূ মোবাইল ওয়ার্কস্পেস লোড হচ্ছে...",
    roleDashboard: "আপনার বরবধূ ড্যাশবোর্ড",
    memberOverview: "মেম্বার সারাংশ",
    adminOverview: "অ্যাডমিন সারাংশ",
    superAdminOverview: "সুপার অ্যাডমিন",
    vendorOverview: "ভেন্ডর সারাংশ",
    vendorProfileLabel: "ভেন্ডর প্রোফাইল",
    ghotokOverview: "ঘটক সারাংশ",
    profileComplete: "প্রোফাইল সম্পূর্ণ",
    profileVisits: "প্রোফাইল ভিজিট",
    interests: "আগ্রহ",
    photoRequests: "ছবি অনুরোধ",
    pendingProfiles: "অপেক্ষমাণ প্রোফাইল",
    collectedAmount: "সংগৃহীত পরিমাণ",
    manualReview: "ম্যানুয়াল রিভিউ",
    members: "মেম্বার",
    vendors: "ভেন্ডর",
    plans: "প্ল্যান",
    revenue: "আয়",
    creditBalance: "ক্রেডিট ব্যালেন্স",
    managedMembers: "ম্যানেজড মেম্বার",
    recentMatches: "সাম্প্রতিক ম্যাচ",
    recentLeads: "সাম্প্রতিক লিড",
    mailbox: "মেইলবক্স",
    wedding: "বিয়ে",
    vendorsDirectory: "ভেন্ডর",
    profileTab: "প্রোফাইল",
    reviewQueue: "রিভিউ কিউ",
    manualPaymentsLabel: "ম্যানুয়াল পেমেন্ট",
    managedList: "ম্যানেজড মেম্বার",
    packagesLabel: "প্যাকেজ",
    overviewTab: "সারাংশ",
    matchesTab: "ম্যাচ",
    leadsTab: "লিড",
    membersTab: "মেম্বার",
    weddingProjects: "বিয়ের প্রজেক্ট",
    vendorShortlists: "ভেন্ডর শর্টলিস্ট",
    conversations: "কথোপকথন",
    profileSettings: "প্রোফাইল সেটিংস",
    partnerPreferences: "পার্টনার পছন্দ",
    photoRequestsLabel: "ছবি অনুরোধ",
    mediaLibrary: "ছবি",
    uploadPhoto: "ছবি আপলোড",
    photoFromPhone: "ফোন থেকে নিন",
    photoFromCamera: "ক্যামেরায় তুলুন",
    membershipPlans: "মেম্বারশিপ প্ল্যান",
    orderHistory: "অর্ডার ইতিহাস",
    messages: "মেসেজ",
    startChat: "চ্যাট শুরু",
    openChat: "চ্যাট খুলুন",
    typeMessage: "মেসেজ লিখুন",
    sendMessage: "মেসেজ পাঠান",
    noConversations: "এখনও কোনো কথোপকথন নেই।",
    noMessages: "এই কথোপকথনে এখনও কোনো মেসেজ নেই।",
    noProjects: "এখনও কোনো বিয়ের প্রজেক্ট নেই।",
    createProject: "প্রজেক্ট তৈরি করুন",
    projectTitle: "প্রজেক্টের নাম",
    guestName: "অতিথির নাম",
    addGuest: "অতিথি যোগ করুন",
    shortlistVendor: "ভেন্ডর শর্টলিস্ট করুন",
    noVendors: "এখনও কোনো ভেন্ডর পাওয়া যায়নি।",
    noReviews: "এখন কোনো অপেক্ষমাণ প্রোফাইল রিভিউ নেই।",
    noPayments: "এখন কোনো ম্যানুয়াল পেমেন্ট অপেক্ষায় নেই।",
    approve: "অনুমোদন",
    reject: "প্রত্যাখ্যান",
    saveProfile: "প্রোফাইল সংরক্ষণ",
    savePreferences: "পছন্দ সংরক্ষণ",
    submitReview: "রিভিউতে পাঠান",
    buyWithAmarPay: "AmarPay দিয়ে কিনুন",
    buyWithPaypal: "PayPal দিয়ে কিনুন",
    buyWithOffice: "অফিস পেমেন্ট",
    buyWithManual: "ম্যানুয়াল পেমেন্ট",
    publicProfile: "পাবলিক প্রোফাইল",
    privateMedia: "প্রাইভেট",
    publicMedia: "পাবলিক",
    makePrimary: "প্রাইমারি করুন",
    incoming: "আসছে",
    outgoing: "পাঠানো",
    ageRange: "বয়স সীমা",
    guardianPhone: "অভিভাবকের ফোন",
    religionLabel: "ধর্ম",
    professionLabel: "পেশা",
    aboutMeLabel: "নিজের সম্পর্কে",
    familyDetailsLabel: "পরিবারের তথ্য",
    aboutPartnerLabel: "সঙ্গী সম্পর্কে",
    locationLabel: "বর্তমান শহর",
    countryCode: "দেশ কোড",
    saveSuccessProfile: "প্রোফাইল সংরক্ষণ হয়েছে।",
    saveSuccessPreference: "পছন্দ সংরক্ষণ হয়েছে।",
    submittedForReview: "প্রোফাইল রিভিউতে পাঠানো হয়েছে।",
    photoRequestApproved: "ছবি অনুরোধ অনুমোদিত হয়েছে।",
    photoRequestDenied: "ছবি অনুরোধ প্রত্যাখ্যাত হয়েছে।",
    mediaUpdated: "ছবির সেটিংস আপডেট হয়েছে।",
    membershipOrderCreated: "মেম্বারশিপ অর্ডার তৈরি হয়েছে।",
    noOrders: "এখনও কোনো মেম্বারশিপ অর্ডার নেই।",
    noMedia: "এখনও কোনো ছবি আপলোড হয়নি।",
    noPhotoRequests: "এখনও কোনো ছবি অনুরোধ নেই।",
    uploadSuccessPhoto: "ছবি আপলোড হয়েছে এবং রিভিউতে গেছে।",
    uploadPermissionError: "ফোন থেকে আপলোড করতে ছবির অনুমতি দরকার।",
    ghotokCreateMember: "ম্যানেজড মেম্বার যোগ করুন",
    ghotokDiscover: "ডিসকভার",
    memberEmailLabel: "মেম্বারের ইমেইল",
    memberPhoneLabel: "মেম্বারের ফোন",
    countryCodeLabel: "দেশ কোড",
    startImpersonation: "ইমপারসোনেশন শুরু",
    endImpersonation: "ইমপারসোনেশন শেষ",
    viewContact: "কন্ট্যাক্ট দেখুন",
    contactUnlocked: "কন্ট্যাক্ট আনলক হয়েছে।",
    activeImpersonationNeeded: "ক্রেডিট ব্যবহার করতে আগে একটি ইমপারসোনেশন সেশন শুরু করুন।",
    noPublicProfiles: "এখন কোনো পাবলিক প্রোফাইল পাওয়া যাচ্ছে না।",
    guardianPhoneLabel: "অভিভাবকের ফোন",
    guardianEmailLabel: "অভিভাবকের ইমেইল",
    impersonationStarted: "ইমপারসোনেশন শুরু হয়েছে।",
    impersonationEnded: "ইমপারসোনেশন শেষ হয়েছে।",
    managedMemberCreated: "ম্যানেজড মেম্বার তৈরি হয়েছে।",
    open: "খোলা",
    responded: "উত্তর দেওয়া হয়েছে",
    booked: "বুকড",
    closeLead: "লিড বন্ধ করুন",
    conversationStarted: "কথোপকথন প্রস্তুত।",
    messageSent: "মেসেজ পাঠানো হয়েছে।",
    projectCreated: "বিয়ের প্রজেক্ট তৈরি হয়েছে।",
    guestAdded: "অতিথি যোগ করা হয়েছে।",
    vendorShortlistedSuccess: "ভেন্ডর শর্টলিস্ট করা হয়েছে।",
    profileApprovedNotice: "প্রোফাইল অনুমোদিত হয়েছে।",
    profileRejectedNotice: "প্রোফাইল প্রত্যাখ্যাত হয়েছে।",
    paymentApprovedNotice: "পেমেন্ট অনুমোদিত হয়েছে।",
    paymentRejectedNotice: "পেমেন্ট প্রত্যাখ্যাত হয়েছে।",
    leadUpdatedNotice: "লিড আপডেট হয়েছে।",
    noManagedMembers: "এখনও কোনো ম্যানেজড মেম্বার নেই।",
    activeImpersonation: "সক্রিয় ইমপারসোনেশন",
    noImpersonation: "কোনো সক্রিয় ইমপারসোনেশন সেশন নেই।",
    guestCount: "অতিথি",
    shortlistCount: "শর্টলিস্ট",
    packageCount: "প্যাকেজ",
    packageNameEn: "প্যাকেজের নাম (EN)",
    packageNameBn: "প্যাকেজের নাম (BN)",
    packageDescEn: "প্যাকেজের বর্ণনা (EN)",
    packageDescBn: "প্যাকেজের বর্ণনা (BN)",
    packagePriceBdt: "মূল্য (BDT)",
    createPackage: "প্যাকেজ তৈরি করুন",
    editPackage: "প্যাকেজ সম্পাদনা",
    updatePackage: "প্যাকেজ আপডেট করুন",
    saveVendorProfile: "ভেন্ডর প্রোফাইল সংরক্ষণ",
    vendorProfileUpdated: "ভেন্ডর প্রোফাইল আপডেট হয়েছে।",
    allLabel: "সব",
    packageCreatedNotice: "ভেন্ডর প্যাকেজ তৈরি হয়েছে।",
    packageStatusUpdated: "প্যাকেজ স্ট্যাটাস আপডেট হয়েছে।",
    packageLoadedForEdit: "প্যাকেজ সম্পাদনার জন্য লোড হয়েছে।",
    noPackages: "এখনও কোনো প্যাকেজ নেই।",
    paymentGatewayPending:
      "অর্ডার তৈরি হয়েছে। টেস্ট স্ট্যাকে গেটওয়ে রিডাইরেক্ট URL পরের ইন্টিগ্রেশন ধাপ।",
    paymentManualPending: "অর্ডার তৈরি হয়েছে এবং অ্যাডমিন অনুমোদনের অপেক্ষায় আছে।",
    leadSource: "লিড উৎস",
    createdOn: "তৈরি হয়েছে",
    lastUpdated: "আপডেট",
    budget: "বাজেট",
    weddingDateLabel: "বিয়ের তারিখ",
    noMatches: "এই মেম্বারের জন্য এখনও কোনো ম্যাচ পাওয়া যায়নি।",
    noLeads: "এখনও কোনো ভেন্ডর লিড নেই।",
    cityPending: "লোকেশন অপেক্ষমাণ",
    liveApiNote: "লাইভ API ডেটা",
    mobileNext:
      "পরের মোবাইল স্লাইসে প্রোফাইল এডিটিং, মিডিয়া আপলোড, পেমেন্ট, এবং আরও গভীর ঘটক/ভেন্ডর অ্যাকশন যোগ হবে।",
    profileStatus: "প্রোফাইল স্ট্যাটাস",
    approvalStatus: "অনুমোদন স্ট্যাটাস",
    billingStatus: "বিলিং স্ট্যাটাস",
    active: "সক্রিয়",
    pending: "অপেক্ষমাণ",
    newLabel: "নতুন",
    manualApproved: "ম্যানুয়ালি অনুমোদিত",
    manualRejected: "ম্যানুয়ালি প্রত্যাখ্যাত",
    approved: "অনুমোদিত",
    rejected: "বাতিল",
    cancelled: "বাতিল",
    inactive: "নিষ্ক্রিয়",
    paid: "পরিশোধিত",
    openStatus: "খোলা",
    closedRejected: "বন্ধ",
    draftStatus: "খসড়া",
    archivedStatus: "আর্কাইভ",
    freeMember: "ফ্রি মেম্বার",
    errorTitle: "মনোযোগ দরকার",
  },
} as const;

export type Copy = {
  [Key in keyof typeof copy.en]: string;
};

export function getCopy(locale: MobileLocale): Copy {
  return copy[locale];
}
